name: CI

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        path: package
    
    - name: Setup Environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.18.3
    
    - name: Install Dependencies
      run: cd package && yarn install
    
    - name: Transpile Code
      run: cd package && yarn build
    
    - name: Create .tar.gz File
      run: tar -czvf package.tar.gz package
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.upload_url }}
        asset_path: ./package.tar.gz
        asset_name: package.tar.gz
        asset_content_type: application/gzip
